<?php return array( 
'JL_WEBNAME' => '湖北华奥安防科技运营股份有限公司',
'JL_BASEHOST' => 'http://www.huaaotech.com',
'JL_COPYRIGHT' => '湖北华奥安防科技运营股份有限公司  版权所有 Copyright © 2017 ',
'JL_KEYWORDS' => '光谷微警务、微警务、微警务平台、指挥警务、平安城市解决方案、智慧城市建设、智慧交通建设、智慧校园建设、智慧城管建设、智慧民政建设、智慧警务建设、智慧便民自助服务设备、平安城市建设、平安城市安防运营服务、城市联网报警运营服务、安防外包运营服务、家居安全运营服务、指尖警务、警务APP、警务系统、掌上警务、社区警务、湖北办证自助服务设备、自助服务终端、自助服务系统、身份证/居住证自助服务设备、社会综合治理解决方案、城市综合治理系统。',
'JL_DESC' => '湖北省国家高新技术企业，平安中国安防运营领导者，致力于智慧城市建设、智慧交通建设、智慧校园建设、智慧城管建设、智慧民政建设、智慧警务建设、智慧便民自助服务设备开发与应用、平安城市建设、平安城市安防运营服务、城市联网报警运营服务、安防外包运营服务、家居安全运营服务等业务。服务电话：400-6633-582，地址：武汉市东湖新技术开发区武汉软件新城B-4栋。',
'SYS_PAGE_SIZE' => '20',
'SYS_ILLEGA_WORDS' => '法轮功|共产党',
'JL_CMSPATH' => '/',
'JL_BEIAN' => '鄂ICP备09026172号-2',
'JL_SERVER' => '0',
'JL_SERVER_HOST' => 'http://localhost/jl_wcs_server/',
'JL_HTML_CACHE' => '0',
'SYS_EMAIL_ACCOUNT' => '546489029',
'SYS_EMAIL_PWD' => 'wybzybhwjmm.',
'SYS_DEFAULT_EDITOR' => '1',
'SYS_CONTENT_PAGE' => '0',
'SYS_FILTER' => '0',
'SYS_SUPER_PWD' => '123',
'SYS_RESET_PWD' => '123456',
'SYS_SAFE_MODE' => '1',
'JL_COLLECT_TITLE' => '默认站点',
'JL_COLLECT_SOURCE' => '默认站点',
'JL_COLLECT_AUTHOR' => '默认站点',
'JL_QQ_LIST' => '小花：78062911
小明：12345678
小张：33333333
小李：12344566
小黄：5321222',
'WEB_WINPOP_SPACE' => '5',
'WEB_WINPOP_TIME' => '1406517128',
'JL_DIANHUA' => '027-65528999',
'JL_DIZHI' => '湖北省武汉市东湖新技术开发区花城大道9号软件新城二期B区4栋',
'SYS_RECYCLE_MODE' => '1',
'JL_WATER_TYPE' => '0',
'JL_WATER_IMG' => '',
'JL_IMGCROP' => '0',
'JL_WATER_TXT' => '京伦科技',
'JL_WATER_FONT' => '',
'JL_WATER_SIZE' => '16',
'JL_WATER_COLOR' => '#000000',
'JL_WATER_OFFSET' => '-3,3',
'JL_WATER_ANGLE' => '0',
'JL_WATER_ALPHA' => '90',
'JL_WATER_POS' => '8',
'JL_IMGCROP_TYPE' => '0',
'JL_IMGCROP_SIZE' => '680,680',
'JL_COUNTER' => '',
'SYS_DATETIME_MODE' => '1',
'JL_TEL' => '027-65526711',
'JL_EMAIL' => 'huaao@huaaotech.com',
'JL_APPURL' => '#',
 ); ?>